version: "3.7"
services:
  prometheus:
    build:
      context: .
      dockerfile: dockerfile
    image: prom
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on: 
      - prometheus